// Mock data para o CardioIA Portal
// Dados clinicamente realistas baseados no dataset PTB-XL

export const mockPatients = [
  {
    id: 1,
    nome: 'Joao Silva Ferreira',
    idade: 58,
    sexo: 'Masculino',
    superclasse: 'MI',
    risco: 'alto',
    ultimoEcg: '2026-03-10',
    bpm: 88,
    cpf: '123.456.789-00',
    telefone: '(11) 99234-5678',
    observacoes: 'Paciente com historico de infarto previo. Em uso de AAS e estatina.',
  },
  {
    id: 2,
    nome: 'Maria Aparecida Santos',
    idade: 72,
    sexo: 'Feminino',
    superclasse: 'HYP',
    risco: 'alto',
    ultimoEcg: '2026-03-12',
    bpm: 76,
    cpf: '234.567.890-11',
    telefone: '(11) 98345-6789',
    observacoes: 'Hipertensao arterial sistemica de longa data. Uso de enalapril e hidroclorotiazida.',
  },
  {
    id: 3,
    nome: 'Carlos Eduardo Lima',
    idade: 45,
    sexo: 'Masculino',
    superclasse: 'NORM',
    risco: 'baixo',
    ultimoEcg: '2026-03-08',
    bpm: 68,
    cpf: '345.678.901-22',
    telefone: '(11) 97456-7890',
    observacoes: 'Check-up de rotina. Sem queixas cardiovasculares.',
  },
  {
    id: 4,
    nome: 'Ana Paula Rodrigues',
    idade: 63,
    sexo: 'Feminino',
    superclasse: 'STTC',
    risco: 'alto',
    ultimoEcg: '2026-03-11',
    bpm: 92,
    cpf: '456.789.012-33',
    telefone: '(21) 99567-8901',
    observacoes: 'Alteracoes isquemicas ST-T em derivacoes V4-V6. Encaminhada para hemodinamica.',
  },
  {
    id: 5,
    nome: 'Roberto Alves Pereira',
    idade: 51,
    sexo: 'Masculino',
    superclasse: 'CD',
    risco: 'alto',
    ultimoEcg: '2026-03-13',
    bpm: 55,
    cpf: '567.890.123-44',
    telefone: '(11) 96678-9012',
    observacoes: 'Bloqueio de ramo esquerdo. Aguarda avaliacao eletrofisiologica.',
  },
  {
    id: 6,
    nome: 'Fernanda Costa Oliveira',
    idade: 38,
    sexo: 'Feminino',
    superclasse: 'NORM',
    risco: 'baixo',
    ultimoEcg: '2026-03-07',
    bpm: 72,
    cpf: '678.901.234-55',
    telefone: '(31) 99789-0123',
    observacoes: 'Avaliacao pre-operatoria. ECG dentro dos limites normais.',
  },
  {
    id: 7,
    nome: 'Paulo Henrique Martins',
    idade: 67,
    sexo: 'Masculino',
    superclasse: 'MI',
    risco: 'alto',
    ultimoEcg: '2026-03-14',
    bpm: 84,
    cpf: '789.012.345-66',
    telefone: '(11) 95890-1234',
    observacoes: 'Infarto inferior antigo, sequela em DII, DIII e aVF. Em acompanhamento cardiologico.',
  },
  {
    id: 8,
    nome: 'Luciana Mendes Carvalho',
    idade: 55,
    sexo: 'Feminino',
    superclasse: 'HYP',
    risco: 'alto',
    ultimoEcg: '2026-03-09',
    bpm: 79,
    cpf: '890.123.456-77',
    telefone: '(41) 99901-2345',
    observacoes: 'Hipertrofia ventricular esquerda confirmada em ecocardiograma.',
  },
  {
    id: 9,
    nome: 'Marcelo Souza Teixeira',
    idade: 42,
    sexo: 'Masculino',
    superclasse: 'INCONCLUSIVO',
    risco: 'baixo',
    ultimoEcg: '2026-03-06',
    bpm: 65,
    cpf: '901.234.567-88',
    telefone: '(11) 94012-3456',
    observacoes: 'Laudo inconclusivo por artefatos de movimento. Repetir exame em 30 dias.',
  },
  {
    id: 10,
    nome: 'Beatriz Almeida Nunes',
    idade: 48,
    sexo: 'Feminino',
    superclasse: 'STTC',
    risco: 'alto',
    ultimoEcg: '2026-03-13',
    bpm: 95,
    cpf: '012.345.678-99',
    telefone: '(51) 99123-4567',
    observacoes: 'Depressao de ST difusa. Historia de angina instavel. Internada para investigacao.',
  },
  {
    id: 11,
    nome: 'Sergio Nascimento Barbosa',
    idade: 70,
    sexo: 'Masculino',
    superclasse: 'CD',
    risco: 'alto',
    ultimoEcg: '2026-03-11',
    bpm: 48,
    cpf: '111.222.333-44',
    telefone: '(11) 93234-5678',
    observacoes: 'BAV de segundo grau Mobitz II. Indicado estudo eletrofisiologico.',
  },
  {
    id: 12,
    nome: 'Claudia Regina Freitas',
    idade: 35,
    sexo: 'Feminino',
    superclasse: 'NORM',
    risco: 'baixo',
    ultimoEcg: '2026-03-05',
    bpm: 70,
    cpf: '222.333.444-55',
    telefone: '(21) 98345-6789',
    observacoes: 'ECG normal. Controle anual recomendado.',
  },
  {
    id: 13,
    nome: 'Eduardo Pinto Goncalves',
    idade: 61,
    sexo: 'Masculino',
    superclasse: 'MI',
    risco: 'alto',
    ultimoEcg: '2026-03-14',
    bpm: 82,
    cpf: '333.444.555-66',
    telefone: '(11) 92456-7890',
    observacoes: 'Infarto anterior extenso. Fracao de ejecao reduzida (35%). Em uso de carvedilol.',
  },
  {
    id: 14,
    nome: 'Patricia Lima Azevedo',
    idade: 53,
    sexo: 'Feminino',
    superclasse: 'INCONCLUSIVO',
    risco: 'baixo',
    ultimoEcg: '2026-03-10',
    bpm: 74,
    cpf: '444.555.666-77',
    telefone: '(31) 97567-8901',
    observacoes: 'Alteracoes inespecificas. Solicitado Holter 24h para complementacao diagnostica.',
  },
  {
    id: 15,
    nome: 'Rodrigo Monteiro Castro',
    idade: 44,
    sexo: 'Masculino',
    superclasse: 'HYP',
    risco: 'alto',
    ultimoEcg: '2026-03-12',
    bpm: 86,
    cpf: '555.666.777-88',
    telefone: '(11) 91678-9012',
    observacoes: 'Hipertrofia biventricular. Cardiopatia hipertensiva em estadio moderado.',
  },
]

export const mockAppointments = [
  {
    id: 1,
    pacienteId: 1,
    pacienteNome: 'Joao Silva Ferreira',
    data: '2026-03-15',
    hora: '08:00',
    tipo: 'Retorno',
    medico: 'Dr. Isaac Maciel',
    status: 'agendada',
    observacoes: 'Revisao de exames pos-cateterismo.',
  },
  {
    id: 2,
    pacienteId: 2,
    pacienteNome: 'Maria Aparecida Santos',
    data: '2026-03-15',
    hora: '09:00',
    tipo: 'Consulta',
    medico: 'Dra. Carla Mendes',
    status: 'realizada',
    observacoes: 'Ajuste de dose anti-hipertensiva.',
  },
  {
    id: 3,
    pacienteId: 4,
    pacienteNome: 'Ana Paula Rodrigues',
    data: '2026-03-15',
    hora: '10:30',
    tipo: 'Urgencia',
    medico: 'Dr. Isaac Maciel',
    status: 'agendada',
    observacoes: 'ECG com alteracoes agudas. Atendimento prioritario.',
  },
  {
    id: 4,
    pacienteId: 5,
    pacienteNome: 'Roberto Alves Pereira',
    data: '2026-03-15',
    hora: '11:00',
    tipo: 'Retorno',
    medico: 'Dr. Felipe Torres',
    status: 'agendada',
    observacoes: 'Resultado de Holter 24h.',
  },
  {
    id: 5,
    pacienteId: 3,
    pacienteNome: 'Carlos Eduardo Lima',
    data: '2026-03-14',
    hora: '14:00',
    tipo: 'Consulta',
    medico: 'Dra. Carla Mendes',
    status: 'realizada',
    observacoes: 'Check-up anual. Sem intercorrencias.',
  },
  {
    id: 6,
    pacienteId: 7,
    pacienteNome: 'Paulo Henrique Martins',
    data: '2026-03-14',
    hora: '15:30',
    tipo: 'Retorno',
    medico: 'Dr. Isaac Maciel',
    status: 'realizada',
    observacoes: 'Revisao de medicacao pos-IAM.',
  },
  {
    id: 7,
    pacienteId: 8,
    pacienteNome: 'Luciana Mendes Carvalho',
    data: '2026-03-13',
    hora: '08:30',
    tipo: 'Consulta',
    medico: 'Dr. Felipe Torres',
    status: 'realizada',
    observacoes: 'Ecocardiograma e ECG de repouso.',
  },
  {
    id: 8,
    pacienteId: 10,
    pacienteNome: 'Beatriz Almeida Nunes',
    data: '2026-03-13',
    hora: '16:00',
    tipo: 'Urgencia',
    medico: 'Dr. Isaac Maciel',
    status: 'realizada',
    observacoes: 'Angina instavel. Admitida na UTI coronariana.',
  },
  {
    id: 9,
    pacienteId: 11,
    pacienteNome: 'Sergio Nascimento Barbosa',
    data: '2026-03-16',
    hora: '09:30',
    tipo: 'Consulta',
    medico: 'Dr. Felipe Torres',
    status: 'agendada',
    observacoes: 'Avaliacao para implante de marcapasso.',
  },
  {
    id: 10,
    pacienteId: 13,
    pacienteNome: 'Eduardo Pinto Goncalves',
    data: '2026-03-16',
    hora: '10:00',
    tipo: 'Retorno',
    medico: 'Dr. Isaac Maciel',
    status: 'agendada',
    observacoes: 'Revisao de exames laboratoriais e ajuste de carvedilol.',
  },
  {
    id: 11,
    pacienteId: 6,
    pacienteNome: 'Fernanda Costa Oliveira',
    data: '2026-03-12',
    hora: '11:00',
    tipo: 'Consulta',
    medico: 'Dra. Carla Mendes',
    status: 'realizada',
    observacoes: 'Avaliacao pre-operatoria liberada.',
  },
  {
    id: 12,
    pacienteId: 9,
    pacienteNome: 'Marcelo Souza Teixeira',
    data: '2026-03-17',
    hora: '14:30',
    tipo: 'Retorno',
    medico: 'Dra. Carla Mendes',
    status: 'agendada',
    observacoes: 'Repeticao de ECG apos reducao de artefatos.',
  },
  {
    id: 13,
    pacienteId: 15,
    pacienteNome: 'Rodrigo Monteiro Castro',
    data: '2026-03-17',
    hora: '08:00',
    tipo: 'Consulta',
    medico: 'Dr. Isaac Maciel',
    status: 'agendada',
    observacoes: 'Primeiro atendimento. Encaminhado pela UBS.',
  },
  {
    id: 14,
    pacienteId: 12,
    pacienteNome: 'Claudia Regina Freitas',
    data: '2026-03-11',
    hora: '15:00',
    tipo: 'Consulta',
    medico: 'Dra. Carla Mendes',
    status: 'cancelada',
    observacoes: 'Cancelado a pedido da paciente. Reagendar.',
  },
  {
    id: 15,
    pacienteId: 14,
    pacienteNome: 'Patricia Lima Azevedo',
    data: '2026-03-18',
    hora: '09:00',
    tipo: 'Retorno',
    medico: 'Dr. Felipe Torres',
    status: 'agendada',
    observacoes: 'Resultado do Holter 24h.',
  },
  {
    id: 16,
    pacienteId: 1,
    pacienteNome: 'Joao Silva Ferreira',
    data: '2026-03-10',
    hora: '08:00',
    tipo: 'Urgencia',
    medico: 'Dr. Isaac Maciel',
    status: 'realizada',
    observacoes: 'Dor precordial aguda. Realizados exames emergenciais.',
  },
  {
    id: 17,
    pacienteId: 2,
    pacienteNome: 'Maria Aparecida Santos',
    data: '2026-03-18',
    hora: '10:00',
    tipo: 'Retorno',
    medico: 'Dr. Isaac Maciel',
    status: 'agendada',
    observacoes: 'Controle de PA apos novo esquema anti-hipertensivo.',
  },
  {
    id: 18,
    pacienteId: 7,
    pacienteNome: 'Paulo Henrique Martins',
    data: '2026-03-19',
    hora: '11:30',
    tipo: 'Consulta',
    medico: 'Dra. Carla Mendes',
    status: 'agendada',
    observacoes: 'Revisao anual e pedido de cintilografia.',
  },
  {
    id: 19,
    pacienteId: 4,
    pacienteNome: 'Ana Paula Rodrigues',
    data: '2026-03-09',
    hora: '14:00',
    tipo: 'Consulta',
    medico: 'Dr. Felipe Torres',
    status: 'cancelada',
    observacoes: 'Cancelado por intercorrencia clinica.',
  },
  {
    id: 20,
    pacienteId: 5,
    pacienteNome: 'Roberto Alves Pereira',
    data: '2026-03-19',
    hora: '16:00',
    tipo: 'Urgencia',
    medico: 'Dr. Isaac Maciel',
    status: 'agendada',
    observacoes: 'Pre-agendado caso necessario apos resultado de Holter.',
  },
]

export const mockDashboardStats = {
  totalPacientes: mockPatients.length,
  consultasHoje: mockAppointments.filter(a => a.data === '2026-03-15').length,
  alertasAltoRisco: mockPatients.filter(p => p.risco === 'alto').length,
  precisaoModelo: '96,2%',
}

export const superclasseColors = {
  MI: '#e63946',
  STTC: '#f4a261',
  CD: '#e9c46a',
  HYP: '#7b2d8b',
  NORM: '#2a9d8f',
  INCONCLUSIVO: '#6c757d',
}

export const superclasseLabels = {
  MI: 'Infarto do Miocardio',
  STTC: 'Isquemia ST-T',
  CD: 'Disturbio de Conducao',
  HYP: 'Hipertrofia',
  NORM: 'Normal',
  INCONCLUSIVO: 'Inconclusivo',
}

export const riskInterpretation = {
  MI: 'Evidencias de infarto do miocardio detectadas pelo modelo CardioIA. Risco cardiovascular ELEVADO. Recomenda-se avaliacao cardiologica imediata, dosagem de troponinas e correlacao clinica.',
  STTC: 'Alteracoes isquemicas ST-T identificadas. Risco cardiovascular ELEVADO. Possivel isquemia ativa ou cronica. Correlacionar com sintomatologia e solicitar exames complementares.',
  CD: 'Disturbio de conducao detectado. Risco cardiovascular ELEVADO. Pode indicar doenca do no sinusal, bloqueios ou cardiomiopatia subjacente. Indicado estudo eletrofisiologico.',
  HYP: 'Criterios de hipertrofia ventricular presentes. Risco cardiovascular ELEVADO. Associado a hipertensao arterial, doenca valvar ou miocardiopatia hipertrofica.',
  NORM: 'ECG dentro dos parametros normais. Risco cardiovascular BAIXO. Manutencao de habitos saudaveis e acompanhamento de rotina recomendados.',
  INCONCLUSIVO: 'Laudo inconclusivo pelo modelo CardioIA. Risco nao determinado. Recomenda-se repeticao do exame com melhor qualidade de sinal e correlacao clinica.',
}
